
public class exceptionex1 {

	public static void main(String[] args) {
		// try,catch문의 사용예를 보여주기 위해 작성한 코드
		try
		{
			try
			{
				
			}
			catch(Exception e)
			{
				
			}
		}
		catch(Exception e)
		{
//			try
//			{
//				
//			}
//			catch(Exception e) //같은 변수명이 선언되어서 오류가 나옴.
//			{
//				
//			}
		}
		
		try
		{
			
		}
		catch(Exception e)
		{
			
		}

	}

}
